FROM rhel7cookedprereq 

RUN mkdir -p dnsb
WORKDIR dnsb

ARG url
RUN curl -o dotnet.tar.gz $url 
RUN tar -xvf dotnet.tar.gz --no-same-owner
RUN rm dotnet.tar.gz

# 1.0, 1.1 build commands
RUN cd * && ./unpack-sources.sh && ./apply-patches.sh &&  ./build.sh || true

