#FROM microsoft/dotnet-buildtools-prereqs:fedora-24-67592e6-20170219020243
FROM microsoft/dotnet-buildtools-prereqs:rhel-7-rpmpkg-e1b4a89-20175311035359
RUN mkdir dnsb
WORKDIR dnsb
RUN yum -y install https://download.microsoft.com/download/5/6/B/56BFEF92-9045-4414-970C-AB31E0FC07EC/dotnet-host-2.0.0-rhel.7-x64.rpm
RUN yum -y install https://download.microsoft.com/download/5/6/B/56BFEF92-9045-4414-970C-AB31E0FC07EC/dotnet-hostfxr-2.0.0-rhel.7-x64.rpm
RUN yum -y install https://download.microsoft.com/download/5/6/B/56BFEF92-9045-4414-970C-AB31E0FC07EC/dotnet-runtime-2.0.0-rhel.7-x64.rpm
RUN yum -y install https://download.microsoft.com/download/5/6/B/56BFEF92-9045-4414-970C-AB31E0FC07EC/aspnetcore-store-2.0.0-rhel.7-x64.rpm
RUN yum -y install https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-rhel-x64.rpm

