FROM rhel74prereq 

RUN mkdir -p dnsb
WORKDIR dnsb

ARG url
RUN curl -o dotnet-1.0.tar.gz $url 
RUN tar -xvf dotnet-1.0.tar.gz

RUN cd * && ./unpack-sources.sh && ./apply-patches.sh &&  ./build.sh || true
