FROM rhel7prereq3 

RUN mkdir -p dnsb
WORKDIR dnsb

RUN curl -LJo dotnet.tar.gz "https://github.com/dotnet/source-build/archive/v2.1.1.tar.gz"
RUN tar -xvf dotnet.tar.gz --no-same-owner
RUN rm dotnet.tar.gz

RUN cd * && ./build.sh /p:ArchiveDownloadedPackages=true || true
RUN cd * && ./build-source-tarball.sh ../tarball-output --skip-build || true
